import { ImageProvider } from "@/context/imageContext";
import "./globals.css";
//import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import { LayerProvider } from "@/context/layerContext";
import { ToastContainer } from "react-toastify";
import { UserContextProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserContextProvider>
        <LayerProvider>
          <ImageProvider>
            <body className={inter.className}>{children}</body>
          </ImageProvider>
        </LayerProvider>
      </UserContextProvider>
    </html>
  );
}
